deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: KmIhJdl3snW4MhGANYuq7BfrDMoNg0o+C4oV0nCjZAlh+EXBOO2Khtmk+DH7nqcWzPCPuc8h2M76phlNR0i8AxHWovqqp83iRMNoGSG1ldxJd7/YrEjH1nKlHd51nSRAYuVP6Ieon0LI9Cl4JPEfk5xTRwzTPPScYTKA7S50TVFfMVsNZYgblH4JLNVvaXG9AACI7DBpB0NFEjI7dRPU3EdaowJJNOgc5ey7V2rPb/xEiiWNQYMCUKPZ+gd+8teODWMj80yPnjuCGJV9L4iP6IM9EwFQ/xj8slmIU63hI2QPhxRG9PN9l+b4iF3xveHFyTjM88zOlV9DL7wKmOCryE/dlmtW3nHcn4xSba75r1Q93oWVibkFy28G4lfLqIGKsD6s68KnkPtM4CiiCaae96uEgVBHGV8+BFOgHxmoBcNQCWPX63rDYDQNn11F1hgmZoyAxU4BkrBWyUF79qwPOKkJQK448tbsXXJcxfTlnfGQnAogwMiVBbzHktVEN+HhlZKKUv3sKVg1UXJAAax/7EazENWm8TrkuqG8C5zdbxpZ5A5VlxeREHPO5eWvs0G4M2LKqfS1ZJ7oqcrXRWgvwUT+hW5WVD/D0MoF28t5xMAzTqcnNujQBst1h8hbcFbmHo1D8+TwUbqdKrhPy7RrhB7ri0Xl5I6GTTyyOoYD5Ic=
  app: entrule-discord
  on:
    repo: GMaiolo/bigote-bot
