language: node_js
node_js:
  - "node"
deploy:
  provider: heroku
  api_key:
    secure: xiaSLY8wt+27ZnBv5l84Ey1FJrba/8ptngjzRfIRsaRF/0UMKbZP7wt2xKdeucNw9LCtn1jH3VCgiqatnJh1W0Mq8jGos3pPD9kVrG26oowWBnaWAgiKXHNGYBpuO3E/zvYbmV5F5sYKPxMa1ORuPWZ0x3Ie8LaHMGKj99l6hX6ueigo7k4oSotM07WP3Mr7jF7SVt3IGLDLTEFKXRw4mMmjsdNDO4LUncM3zzU8xxDceCDAAJPz1mxd2gLQnW6O/9lPq86vdKHVOohl6njOvYxO0Cwkx0JC1ty6RBR/YghbN40z0SwPjU06GenVNgYyK8bVzCFE+T9m8RxmEtZEEwNb/brUeUJdzFM2ELKdbuC+8mAkQxzU6GtuZQSmXwAq6WRuu8CbQeTYX5v1IvyZE2RXMr0Z8jIurKbzAGedopd+2rm7yWc4q5zBLL4hgOexFaRWcrkFz/RQ++f7TGqsmwSdUKVw2QzIcDufFV6QjvLBkMbL23Zkj7Xis5Ttqirgn/k3Rl6p06kdJ4N79EvjWS47fFG59Xz7dRufJZ4/4wsKJum0kIDHwIRhBt+0mp8cHXje276ZzcWwleb6sbcediroO/b9BLwEkL0x842dSeTRPVtv3BorsdOErqNojryJpQbnccf1cEr0BFZaEYqWVLJBqd6in+PW/fkE4RI6aIk=
  app: entrule-discord
  on:
    repo: GMaiolo/bigote-bot
